# Generated by Django 5.2 on 2025-05-07 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_departments', to='letter.department')),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_sadira', models.CharField(max_length=100, unique=True)),
                ('number_warida', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('letter_type', models.CharField(choices=[('maktob', 'Maktob'), ('estilam', 'Estilam'), ('peshnihad', 'Peshnihad')], max_length=20)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('sender_date', models.DateField()),
                ('receiver_date', models.DateField()),
                ('attach', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('receiver_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_letters', to='letter.department')),
                ('sender_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_letters', to='letter.department')),
            ],
        ),
        migrations.CreateModel(
            name='LetterTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateField()),
                ('received_date', models.DateField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('received', 'Received'), ('delivered', 'Delivered')], max_length=20)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='letter.letter')),
                ('receiver_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_received', to='letter.department')),
                ('sender_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_sent', to='letter.department')),
            ],
        ),
    ]
